# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-19 09:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Session',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('date', models.DateTimeField(verbose_name='Date and time')),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=90)),
                ('lastname', models.CharField(max_length=80)),
                ('email', models.EmailField(max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=60)),
                ('date', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='session',
            name='students',
            field=models.ManyToManyField(to='workshops.Student'),
        ),
        migrations.AddField(
            model_name='session',
            name='topic',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='workshops.Topic'),
        ),
    ]
